Unstructured-IO/unstructured-api-tools

README.md
Adds an explicit link to the security policy in the`README` for the repo.
=> docs: Link to security policy in the README

.github/dependabot.yml
Addresses [CORE-53](https://unstructured-ai.atlassian.net/browse/CORE-53). Configures dependabot scans for the repo. Dependabot is set up to check for `pip-compile` and GitHub actions updates once a week.
=> build: Configure dependabot scan

Makefile, scripts/version-sync.sh
Addresses [Core-280](https://unstructured-ai.atlassian.net/browse/CORE-280).
Similar to [`unstructured` PR #25](https://github.com/Unstructured-IO/unstructured/pull/25), adds a script to check version in `CHANGELOG.md` against version in `__version__.py` or overwrite the latter version. I made a slight change in the script giving an optional variable to specify the location of `__version__.py` so the same script can be used more universally. Same make targets are added, and the check is added to the `make check` target, and consequently becomes part of CI.
The testing instructions are the same as the other PR:
To check script:
1. Change the version in `__version__.py` to an invalid version.
2. Run `make check-version`.
3. Should fail with an error message indicating valid semver could not …
=> feat: version sync

.gitignore, CHANGELOG.md, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
- Removes the `import inspect` line from the template because `inspect` no longer happens on the fly
- Updates the `.gitignore` to include temporary files that get generated by the tests
=> chore: Remove unused inspect import

CHANGELOG.md, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
Removes the rate limit on the healthcheck endpoint. This was causing occasional `429` responses in the deployed healthcheck in ECS.
=> fix: Remove ratelimit on the healthcheck endpoint

.github/workflows/ci.yml, CHANGELOG.md, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/convert.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
`response_type` is passed in a dict `optional_param_value_map`, we should get its value when we first use it in the template.
can convert this block in a pipeline notebook to an api script
```
def pipeline_api(text,file, response_type="text/csv", m_subject=[], m_name=[]):
return {"message": "Got request"}
```
=> fix: get `response_type` value before first call

CHANGELOG.md, test_unstructured_api_tools/pipelines/test_convert.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/convert.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
Resolves https://github.com/Unstructured-IO/community/issues/23
**Summary of changes**
- Add support for `response_schema` parameter in pipeline API functions that is passed in the API request as `output_schema`.
- Update unit tests
- Update version and changelog
**Testing**
- Create a test notebook in `pipeline-sec-filings/pipeline-notebooks` directory called `pipeline-test.ipynb` and paste the following contents:
```python
def pipeline_api(text, file=None, m_var=[], response_schema="label_studio"):
return {"message": f"Returning response with schema: {response_schema}", "var": m_var}
```
- Run `make generate-api` and run `PYTHONPATH=. uvicorn prepline_sec_filings.api.test:app --reload`
- Send a request to `http://localhost:8000/sec-filings/v0.2.0/test` with and without `output_schema` …
=> feat: Add support for output_schema parameter

CHANGELOG.md, unstructured_api_tools/__version__.py, unstructured_api_tools/cli.py
Previously, FastAPI code generated by this tool (notably `prepline_<project>/api/app.py`) would produce
slightly different versions when run on Mac vs. Linux. This was due to do the ambiguous ordering of filenames returned
by `os.listdir` in `unstructured_api_tools/cli.py`. Now, the filenames are sorted, so templates dependent on iterating
through filenames are consistent.
Ref:
https://github.com/Unstructured-IO/unstructured-api-tools/blob/c3c08ba/unstructured_api_tools/cli.py#L35
=> fix: consistent generated code across OS's

CHANGELOG.md, test_unstructured_api_tools/api/test_docs.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/app.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/api_conventions.py, unstructured_api_tools/pipelines/convert.py, unstructured_api_tools/pipelines/templates/pipeline_app.txt
Added dynamic `docs_url`, which is related to `pipeline_family`. If pipeline_family isn't defined, docs_url will equal `/docs`. 
Added test for testing dynamic doc url.
Updated test API.
Bumped version from 0.6.0 to 0.7.0 
Closes issue #146
=> added dynamic docs_url

CHANGELOG.md, test_unstructured_api_tools/api/test_file_apis.py, test_unstructured_api_tools/api/test_file_text_apis.py, test_unstructured_api_tools/api/test_text_apis.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_5.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_4.py, test_unstructured_api_tools/pipelines/test_api_conventions.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/api_conventions.py, unstructured_api_tools/pipelines/convert.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
Added generating duplicate routes with semver major version. 
Updated tests for endpoints and generating pipeline_path. Added additional test for validating generation shorter pipeline_path.
Bumped version from 0.7.0 to 0.8.0
Closes #147
=> Add duplicate routes with semver major version

CHANGELOG.md, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/app.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_5.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_4.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt, unstructured_api_tools/pipelines/templates/pipeline_app.txt
Removed async/await from endpoints. 
Updated templates for generating test API.
Removed duplicated code from templates for creating additional endpoint with shorter semver (mentioned in comment https://github.com/Unstructured-IO/unstructured-api-tools/pull/149#pullrequestreview-1357536942).
Bump version to 0.8.1
=> Remove async/await

CHANGELOG.md, test_unstructured_api_tools/pipeline-test-project/pipeline-notebooks/pipeline-process-file-1.ipynb, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_1.py, test_unstructured_api_tools/pipelines/test_convert.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/convert.py
Before this fix, one could not `import os` in a `# pipeline-api` as the resulting FastAPI python module would then have `import os` defined twice. But, in the case where`# pipeline-api` cell had a reference to an `os` module that had been imported previously in a non-`# pipeline-api` cell, an error occurred when converting the notebook since `os` had not been defined (as only `# pipeline-api` cells are inspected, per design).
The fix is to include implied "standard" imports for `os`, `gzip`, `mimetypes`, and `json` when inferring parameters in `pipeline_api`, but not when executing the jinja pipeline-template logic since those imports already exist at the top of the template.
=> fix: standard import ref's accessible in api cells

CHANGELOG.md, test_unstructured_api_tools/api/test_file_apis.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_5.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_4.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
Currently when a request fails because a file's mimetype is not in UNSTRUCTURED_ALLOWED_MIMETYPES we log an error message with the filename. Debugging issues related to this could be made easier by including the content_type in the error message.
* Adds content_type to error message for unsupported file types
* Updates tests to validate this error message.
=> chore: add content_type to error message

.github/workflows/ci.yml
Added supporting python versions 3.8, 3.9, and 3.10 for CI
---
Closes issue https://github.com/Unstructured-IO/unstructured-api-tools/issues/139
=> Python versions 3.8, 3.9 and 3.10 should be tested in CI #139

CHANGELOG.md, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/app.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_app.txt
Removed /healthcheck endpoint from swagger.
Updated template for generating app.py and CHANGELOG.md
---
Closes issue #151
=> /healthcheck should not be visible in the /<pipeline-family>/docs #151

CHANGELOG.md, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_5.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_4.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
I can't reproduce this with the Starlette test client, but the following snippet in a python shell is returning a 400 error from the hosted api.
```
import requests
filename="fake.doc"
with open(filename, "rb") as f:
response = requests.post(
"https://api.unstructured.io/general/v0/general",
files={"files": (str(filename), f)},
)
print(response.text)
```
When we don't specify the content type in requests, it's causing the FastAPI file.content_type to be
None, at least on my machine.
=> fix: handle case where file.content_type is None

CHANGELOG.md, test_unstructured_api_tools/api/test_docs.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/app.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_app.txt
For instance, if we want the swagger ui to load at /general/docs, we should make sure the spec is pulled from /general/openapi.json.
=> chore: add dynamic openapi_url to mirror docs_url

CHANGELOG.md, test_unstructured_api_tools/api/test_file_apis.py, test_unstructured_api_tools/api/test_file_text_apis.py, test_unstructured_api_tools/api/test_text_apis.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_5.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_4.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
Added ability to request one file as multipart/form data. 
Updated tests and template for generating test API, replaced `return PlainTextResponse` with `raise HTTPException`.
Bump version from 0.10.0 to 0.10.1
---
Closes issue #165
=> Ability to request one file as multipart/form data #165

CHANGELOG.md, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/app.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_app.txt
Reduce noisy uvicorn logs when polling /healthcheck.
To test, you can run a local copy of api-tools to regenerate one of the pipeline apis, and try calling /healthcheck on it.
For instance, in api-tools, run `make install-project-local`. Jump over to unstructured-api and run `make generate-api` and `make run-web-app`. Make a request to localhost:8000/healthcheck and verify that the uvicorn logs do not show it.
Source: https://github.com/encode/starlette/issues/864#issuecomment-653076434
=> chore: Filter out logs on /healthcheck

CHANGELOG.md, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/app.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/templates/pipeline_app.txt
Testing steps!
* activate pyenv for `unstructured-api` (not `-tools`) and cd to root dir of `unstructured-api-tools` to run `pip install -e .` to install the current branch. (should see __version__.py ( 0.10.5 ) from this branch match output from pip list)
* in the `unstructured-api` dir, run make generate-api
* export ALLOWED_ORIGINS="http://example.com/,http://amanda.com" (important that the env var is a comma separated str) and start the app locally with make run-web-app
* run curl and POST and OPTION requests to show the Access-Control-Allow-Origin header being set
example curl request:
should see 200:
```
curl -X OPTIONS -H "Origin: http://example.com" -H "Access-Control-Request-Method: POST" -i http://localhost:8000/general/v0/general
curl -X OPTIONS -H "Origin: http://amanda.com" …
```
=> chore: updating env var processing for CORS

CHANGELOG.md, test_unstructured_api_tools/api/test_file_apis.py, test_unstructured_api_tools/api/test_file_text_apis.py, test_unstructured_api_tools/api/test_text_apis.py, test_unstructured_api_tools/pipeline-test-project/pipeline-notebooks/pipeline-process-file-3.ipynb, test_unstructured_api_tools/pipeline-test-project/pipeline-notebooks/pipeline-process-text-3.ipynb, test_unstructured_api_tools/pipeline-test-project/pipeline-notebooks/pipeline-process-text-file-3.ipynb, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_3.py, test_unstructured_api_tools/pipelines/test_convert.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/convert.py, unstructured_api_tools/pipelines/templates/pipeline_api.txt
If request is included as a non-default param to pipeline_api, we'll send the active Request object. This will allow a pipeline to, for instance, access headers as needed.
If you'd like to try this:
* Pull this branch
* Active your pyenv for `unstructured-api` and run `make install-project-local`
* Switch to `unstructured-api` and verify that nothing changes when you run `make generate-api`
* Now, open the pipeline notebook and add `request` as a param to `pipeline_api`:
```
def pipeline_api(
file,
request,
filename='',
m_strategy=[],
m_coordinates=[],
file_content_type=None,
response_type="application/json"
):
```
* Regenerate the api and verify that `general.py` now takes the request param.
=> feat: allow a pipeline to optionally use the FastAPI Request object

CHANGELOG.md, Makefile, requirements/base.txt, setup.py, test_unstructured_api_tools/pipeline-test-project/pipeline-notebooks/pipeline-process-file-1.ipynb, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_file_5.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_4.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_1.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_2.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_3.py, test_unstructured_api_tools/pipeline-test-project/prepline_test_project/api/process_text_file_4.py, unstructured_api_tools/__version__.py, unstructured_api_tools/pipelines/convert.py, unstructured_api_tools/pipelines/lint.py
Right now if the jupyter notebook cell containes an import that was already being added by the template, this would cause a linting error due to duplicate imports. This PR adds in autoflake to run unused import and variable removal as well as provide code to use for removing duplicate imports manually.
=> Add autoflake formatting with duplicate import removal
